<a href="https://colab.research.google.com/github/hananbahtiti/School/blob/main/School.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/hananbahtiti/School.git

Cloning into 'School'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 40.56 KiB | 2.90 MiB/s, done.

In [3]:
import pandas as pd
from sklearn import preprocessing

In [4]:

file = '/content/School/General_Education_School.csv'
df = pd.read_csv(file)

print(f"{df.info()}")

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1671 entries, 0 to 1670
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DBN                                1671 non-null   object
 1   School Name                        1671 non-null   object
 2   School Type                        1670 non-null   object
 3   Parent Response Rate               1671 non-null   object
 4   Teacher Response Rate              1671 non-null   object
 5   Student Response Rate              996 non-null    object
 6   Total Safety and Respect Score     1671 non-null   object
 7   Total Communication Score          1671 non-null   object
 8   Total Engagement Score             1671 non-null   object
 9   Total Academic Expectations Score  1671 non-null   object
dtypes: object(10)
memory usage: 130.7+ KB
None

,DBN,School Name,School Type,Parent Response Rate,Teacher Response Rate,Student Response Rate,Total Safety and Respect Score,Total Communication Score,Total Engagement Score,Total Academic Expectations Score
0,dbn,locationname,NaN,rr_p,rr_t,rr_s,saf_tot_12,com_tot_12,eng_tot_12,aca_tot_12
1,01M015,P.S. 015 Roberto Clemente,Elementary School,61%,92%,NaN,8.4,8.2,8.3,8.2
2,01M019,P.S. 019 Asher Levy,Elementary School,92%,94%,NaN,8.4,8,8,8.2
3,01M020,P.S. 020 Anna Silver,Elementary School,88%,73%,NaN,8.5,7.8,8.2,8.2
4,01M034,P.S. 034 Franklin D. Roosevelt,Elementary/Middle School,39%,58%,96%,7.3,6.9,7.3,7.7

In [5]:
print(f"counts valus null: \n { df.isnull().sum() / len(df) * 100}")

counts valus null:
 DBN                                   0.000000
School Name                           0.000000
School Type                           0.059844
Parent Response Rate                  0.000000
Teacher Response Rate                 0.000000
Student Response Rate                40.394973
Total Safety and Respect Score        0.000000
Total Communication Score             0.000000
Total Engagement Score                0.000000
Total Academic Expectations Score     0.000000
dtype: float64

In [6]:
for col in df.columns:
  print(f'================= {col} =================')
  print(f'{df[col].value_counts()}')

================= DBN =================
DBN
84M483    2
84M482    2
84M481    2
24Q012    1
24Q007    1
         ..
10X696    1
10X667    1
10X660    1
10X549    1
11X089    1
Name: count, Length: 1668, dtype: int64
================= School Name =================
School Name
New York French American Charter School               2
Harlem Success Academy Charter School 5               2
P.S. 212                                              2
Democracy Preparatory Harlem Charter School           2
P.S. 253                                              2
                                                     ..
Grace Dodge Yabc                                      1
Grace Dodge Career And Technical Education High Sc    1
Discovery High School                                 1
Bronx Theatre High School                             1
P.S. 087 Bronx                                        1
Name: count, Length: 1666, dtype: int64
================= School Type =================
School Type
Elementary School                617
High School                      352
Middle School                    293
Elementary/Middle School         160
Middle/High School                87
Early Childhood School            83
Transfer High School              49
YABC                              22
Elementary/Middle/High School      7
Name: count, dtype: int64
================= Parent Response Rate =================
Parent Response Rate
100%    45
58%     35
73%     32
45%     30
63%     29
        ..
10%      3
3%       3
4%       3
8%       2
rr_p     1
Name: count, Length: 101, dtype: int64
================= Teacher Response Rate =================
Teacher Response Rate
100%    334
96%      84
88%      68
97%      60
93%      52
       ...
30%       1
8%        1
2%        1
19%       1
29%       1
Name: count, Length: 84, dtype: int64
================= Student Response Rate =================
Student Response Rate
99%    61
96%    60
95%    57
97%    55
98%    55
       ..
44%     1
45%     1
13%     1
23%     1
51%     1
Name: count, Length: 75, dtype: int64
================= Total Safety and Respect Score =================
Total Safety and Respect Score
8.3           98
8.2           93
7.7           90
8             87
7.6           80
8.1           79
8.4           78
8.5           74
7.8           73
7.9           73
7.5           69
7.3           63
8.6           62
8.7           61
7.4           58
7.2           53
6.9           53
8.8           52
7.1           45
7             42
6.8           29
6.7           28
8.9           27
9.1           24
9             23
6.4           22
6.5           21
6.6           21
9.2           21
9.3           12
6.2           10
6.3           10
9.4            9
6.1            7
6              6
9.5            5
5.7            5
saf_tot_12     1
5.5            1
5.8            1
5.9            1
4.7            1
5.6            1
9.6            1
5.4            1
Name: count, dtype: int64
================= Total Communication Score =================
Total Communication Score
7.4           101
7              97
7.3            95
7.2            92
7.5            89
6.9            84
6.8            78
7.1            74
7.7            74
7.6            73
6.7            71
6.6            68
7.8            67
7.9            65
8.1            62
6.5            55
6.4            51
8              49
8.3            39
8.2            38
8.4            31
8.5            30
6.3            27
6.1            23
6.2            19
8.7            19
5.9            19
6              16
8.6            12
8.8            10
5.7             8
8.9             8
9               6
5.8             4
5.6             3
5.5             3
9.2             3
5.4             2
9.1             2
com_tot_12      1
5               1
5.1             1
4.7             1
Name: count, dtype: int64
================= Total Engagement Score =================
Total Engagement Score
7.6           102
7.5           101
7.8           100
7.4            95
8              94
7.2            94
7.3            91
7.1            83
7              82
7.7            76
7.9            74
8.1            71
8.2            68
6.9            59
8.3            54
8.4            52
6.8            48
8.5            40
6.7            39
8.6            32
6.6            32
8.8            26
9.1            20
8.7            20
6.3            19
6.4            17
6.5            16
8.9            14
6.2            12
9               8
6.1             7
6               7
5.9             5
5.8             4
9.2             2
5.3             2
eng_tot_12      1
5.6             1
4.8             1
9.3             1
5.7             1
Name: count, dtype: int64
================= Total Academic Expectations Score =================
Total Academic Expectations Score
7.7           115
8.2           112
7.9           101
8.1            99
7.8            93
7.6            93
8              92
7.5            90
8.3            90
7.4            88
8.4            78
8.5            70
7.3            65
8.6            56
7.2            56
8.7            52
7.1            43
8.8            33
6.9            31
7              28
8.9            25
9              22
9.2            21
6.8            21
9.1            18
6.6            15
6.7            15
6.5            11
6.4             9
6.3             8
9.3             6
6.1             5
6.2             3
aca_tot_12      1
5.5             1
5.8             1
9.5             1
9.4             1
5.3             1
6               1
Name: count, dtype: int64

In [8]:
print(f" {df.nunique()}")

 DBN                                  1668
School Name                          1666
School Type                             9
Parent Response Rate                  101
Teacher Response Rate                  84
Student Response Rate                  75
Total Safety and Respect Score         45
Total Communication Score              43
Total Engagement Score                 41
Total Academic Expectations Score      40
dtype: int64

In [1]:
df = df.copy()
# Instead of dropping by index label, use .iloc to select all rows from the second one onwards
# This effectively removes the first row by its integer position
df = df.iloc[1:].copy()
df.info()
df.head()

NameError: name 'df' is not defined

In [ ]:
df[['Total Academic Expectations Score', 'Total Engagement Score', 'Total Communication Score', 'Total Safety and Respect Score']] = df[['Total Academic Expectations Score', 'Total Engagement Score', 'Total Communication Score', 'Total Safety and Respect Score']].astype(float)
df[['Student Response Rate', 'Teacher Response Rate', 'Parent Response Rate']] = df[['Student Response Rate', 'Teacher Response Rate', 'Parent Response Rate']].replace(r'%', '', regex=True).apply(pd.to_numeric, errors="coerce")
print(f"{df.info()}")
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1669 entries, 2 to 1670
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DBN                                1669 non-null   object
 1   School Name                        1669 non-null   object
 2   School Type                        1669 non-null   object
 3   Parent Response Rate               1669 non-null   int64
 4   Teacher Response Rate              1669 non-null   int64
 5   Student Response Rate              995 non-null    float64
 6   Total Safety and Respect Score     1669 non-null   float64
 7   Total Communication Score          1669 non-null   float64
 8   Total Engagement Score             1669 non-null   float64
 9   Total Academic Expectations Score  1669 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 130.5+ KB
None
      DBN                     School Name               School Type  \
2  01M019             P.S. 019 Asher Levy         Elementary School
3  01M020            P.S. 020 Anna Silver         Elementary School
4  01M034  P.S. 034 Franklin D. Roosevelt  Elementary/Middle School
5  01M063       P.S. 063 William Mckinley         Elementary School
6  01M064           P.S. 064 Robert Simon         Elementary School

   Parent Response Rate  Teacher Response Rate  Student Response Rate  \
2                    92                     94                    NaN
3                    88                     73                    NaN
4                    39                     58                   96.0
5                    58                    100                    NaN
6                    50                     94                    NaN

   Total Safety and Respect Score  Total Communication Score  \
2                             8.4                        8.0
3                             8.5                        7.8
4                             7.3                        6.9
5                             8.5                        7.4
6                             8.6                        7.9

   Total Engagement Score  Total Academic Expectations Score
2                     8.0                                8.2
3                     8.2                                8.2
4                     7.3                                7.7
5                     7.6                                7.8
6                     8.1                                8.2

In [ ]:
df.describe()

,Parent Response Rate,Teacher Response Rate,Student Response Rate,Total Safety and Respect Score,Total Communication Score,Total Engagement Score,Total Academic Expectations Score
count,1669.000000,1669.000000,995.000000,1669.000000,1669.000000,1669.000000,1669.000000
mean,56.362493,83.405033,84.544724,7.850030,7.299281,7.580947,7.879029
std,25.017161,17.432332,16.129966,0.745801,0.697701,0.663286,0.625539
min,1.000000,0.000000,0.000000,4.700000,4.700000,4.800000,5.300000
25%,37.000000,75.000000,79.000000,7.300000,6.800000,7.100000,7.500000
50%,57.000000,88.000000,90.000000,7.900000,7.300000,7.600000,7.900000
75%,76.000000,97.000000,96.000000,8.400000,7.800000,8.000000,8.300000
max,100.000000,100.000000,100.000000,9.600000,9.200000,9.300000,9.500000

In [ ]:
label_encoder = preprocessing.LabelEncoder()
df['School Type']= label_encoder.fit_transform(df['School Type'])
df.head()

,DBN,School Name,School Type,Parent Response Rate,Teacher Response Rate,Student Response Rate,Total Safety and Respect Score,Total Communication Score,Total Engagement Score,Total Academic Expectations Score
2,01M019,P.S. 019 Asher Levy,1,92,94,NaN,8.4,8.0,8.0,8.2
3,01M020,P.S. 020 Anna Silver,1,88,73,NaN,8.5,7.8,8.2,8.2
4,01M034,P.S. 034 Franklin D. Roosevelt,2,39,58,96.0,7.3,6.9,7.3,7.7
5,01M063,P.S. 063 William Mckinley,1,58,100,NaN,8.5,7.4,7.6,7.8
6,01M064,P.S. 064 Robert Simon,1,50,94,NaN,8.6,7.9,8.1,8.2