In [ ]:
!git clone https://github.com/hananbahtiti/School.git

Cloning into 'School'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 52.59 KiB | 3.76 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [ ]:
import pandas as pd
from sklearn import preprocessing
import seaborn as sns
import matplotlib.pyplot as plt

# Data Dictionary / Column Descriptions

| Column Name                          | Description                                                                                          |
|------------------------------------|----------------------------------------------------------------------------------------------------|
| **DBN**                            | District Borough Number â€” unique identifier assigned to each school within the NYC Department of Education system. |
| **School Name**                    | The official full name of the school.                                                              |
| **School Type**                    | Classification of the school, such as Elementary, Middle, or High School.                           |
| **Parent Response Rate** (%)      | Percentage of parents who responded to the school survey, indicating parent engagement.            |
| **Teacher Response Rate** (%)     | Percentage of teachers who participated in the survey, reflecting staff involvement.               |
| **Student Response Rate** (%)     | Percentage of students who completed the survey, measuring student participation.                   |
| **Total Safety and Respect Score**| Aggregate score assessing perceptions of safety and respect within the school environment.         |
| **Total Communication Score**     | Score evaluating the effectiveness of communication between the school, families, and staff.       |
| **Total Engagement Score**        | Score measuring the level of engagement among students, families, and staff.                        |
| **Total Academic Expectations Score** | Score representing the academic expectations and rigor promoted by the school.                  |

In [ ]:
# Load the dataset from the specified CSV file path into a DataFrame
file = '/content/School/General_Education_School.csv'
df = pd.read_csv(file)

# Display a concise summary of the DataFrame including column names, data types, and non-null counts
print(f"{df.info()}")

# Display the first five rows of the dataset for a quick preview of the data
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1671 entries, 0 to 1670
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DBN                                1671 non-null   object
 1   School Name                        1671 non-null   object
 2   School Type                        1670 non-null   object
 3   Parent Response Rate               1671 non-null   object
 4   Teacher Response Rate              1671 non-null   object
 5   Student Response Rate              996 non-null    object
 6   Total Safety and Respect Score     1671 non-null   object
 7   Total Communication Score          1671 non-null   object
 8   Total Engagement Score             1671 non-null   object
 9   Total Academic Expectations Score  1671 non-null   object
dtypes: object(10)
memory usage: 130.7+ KB
None

,DBN,School Name,School Type,Parent Response Rate,Teacher Response Rate,Student Response Rate,Total Safety and Respect Score,Total Communication Score,Total Engagement Score,Total Academic Expectations Score
0,dbn,locationname,NaN,rr_p,rr_t,rr_s,saf_tot_12,com_tot_12,eng_tot_12,aca_tot_12
1,01M015,P.S. 015 Roberto Clemente,Elementary School,61%,92%,NaN,8.4,8.2,8.3,8.2
2,01M019,P.S. 019 Asher Levy,Elementary School,92%,94%,NaN,8.4,8,8,8.2
3,01M020,P.S. 020 Anna Silver,Elementary School,88%,73%,NaN,8.5,7.8,8.2,8.2
4,01M034,P.S. 034 Franklin D. Roosevelt,Elementary/Middle School,39%,58%,96%,7.3,6.9,7.3,7.7

#**1. Data Cleaning**

In [ ]:
# Create a copy of the original DataFrame to avoid modifying it directly
df = df.copy()

# Remove the first row based on its integer position using .iloc
# This is useful when the first row contains metadata or is not part of the actual data
df = df.iloc[1:].copy()

# Display the structure of the DataFrame after removing the first row
df.info()

# Display the first five rows of the updated DataFrame to verify the changes
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670 entries, 1 to 1670
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DBN                                1670 non-null   object
 1   School Name                        1670 non-null   object
 2   School Type                        1670 non-null   object
 3   Parent Response Rate               1670 non-null   object
 4   Teacher Response Rate              1670 non-null   object
 5   Student Response Rate              995 non-null    object
 6   Total Safety and Respect Score     1670 non-null   object
 7   Total Communication Score          1670 non-null   object
 8   Total Engagement Score             1670 non-null   object
 9   Total Academic Expectations Score  1670 non-null   object
dtypes: object(10)
memory usage: 130.6+ KB

,DBN,School Name,School Type,Parent Response Rate,Teacher Response Rate,Student Response Rate,Total Safety and Respect Score,Total Communication Score,Total Engagement Score,Total Academic Expectations Score
1,01M015,P.S. 015 Roberto Clemente,Elementary School,61%,92%,NaN,8.4,8.2,8.3,8.2
2,01M019,P.S. 019 Asher Levy,Elementary School,92%,94%,NaN,8.4,8,8,8.2
3,01M020,P.S. 020 Anna Silver,Elementary School,88%,73%,NaN,8.5,7.8,8.2,8.2
4,01M034,P.S. 034 Franklin D. Roosevelt,Elementary/Middle School,39%,58%,96%,7.3,6.9,7.3,7.7
5,01M063,P.S. 063 William Mckinley,Elementary School,58%,100%,NaN,8.5,7.4,7.6,7.8

In [ ]:
# Convert selected survey score columns to float type for accurate numerical analysis
df[['Total Academic Expectations Score',
    'Total Engagement Score',
    'Total Communication Score',
    'Total Safety and Respect Score']] = df[[
        'Total Academic Expectations Score',
        'Total Engagement Score',
        'Total Communication Score',
        'Total Safety and Respect Score'
    ]].astype(float)

# Remove percentage signs and convert response rate columns to integers
# 'errors="coerce"' will convert any invalid entries to NaN
df[['Student Response Rate',
    'Teacher Response Rate',
    'Parent Response Rate']] = df[[
        'Student Response Rate',
        'Teacher Response Rate',
        'Parent Response Rate'
    ]].replace(r'%', '', regex=True).astype('Int64')  # Use nullable integer type


# Display a concise summary of the DataFrame including updated data types and null counts
print(f"{df.info()}")

# Display the first five rows to confirm the changes and inspect data quality
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670 entries, 1 to 1670
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DBN                                1670 non-null   object
 1   School Name                        1670 non-null   object
 2   School Type                        1670 non-null   object
 3   Parent Response Rate               1670 non-null   Int64
 4   Teacher Response Rate              1670 non-null   Int64
 5   Student Response Rate              995 non-null    Int64
 6   Total Safety and Respect Score     1670 non-null   float64
 7   Total Communication Score          1670 non-null   float64
 8   Total Engagement Score             1670 non-null   float64
 9   Total Academic Expectations Score  1670 non-null   float64
dtypes: Int64(3), float64(4), object(3)
memory usage: 135.5+ KB
None
      DBN                     School Name               School Type  \
1  01M015       P.S. 015 Roberto Clemente         Elementary School
2  01M019             P.S. 019 Asher Levy         Elementary School
3  01M020            P.S. 020 Anna Silver         Elementary School
4  01M034  P.S. 034 Franklin D. Roosevelt  Elementary/Middle School
5  01M063       P.S. 063 William Mckinley         Elementary School

   Parent Response Rate  Teacher Response Rate  Student Response Rate  \
1                    61                     92                   <NA>
2                    92                     94                   <NA>
3                    88                     73                   <NA>
4                    39                     58                     96
5                    58                    100                   <NA>

   Total Safety and Respect Score  Total Communication Score  \
1                             8.4                        8.2
2                             8.4                        8.0
3                             8.5                        7.8
4                             7.3                        6.9
5                             8.5                        7.4

   Total Engagement Score  Total Academic Expectations Score
1                     8.3                                8.2
2                     8.0                                8.2
3                     8.2                                8.2
4                     7.3                                7.7
5                     7.6                                7.8

In [ ]:
# Remove duplicate rows from the DataFrame to ensure data integrity
df = df.drop_duplicates()

# Display concise summary of the DataFrame including column types and non-null counts
df.info()

In [ ]:
# Remove the 'School Name' column from the DataFrame as it is no longer needed for analysis.
# The 'axis=1' parameter specifies that a column (not a row) is being dropped.
# 'inplace=True' ensures the change is applied directly to the original DataFrame without needing reassignment.
df.drop('School Name', axis=1, inplace=True)

# Display summary information about the DataFrame after removing the column,
# including the number of entries, column data types, and memory usage.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1667 entries, 1 to 1667
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DBN                                1667 non-null   object
 1   School Name                        1667 non-null   object
 2   School Type                        1667 non-null   object
 3   Parent Response Rate               1667 non-null   Int64
 4   Teacher Response Rate              1667 non-null   Int64
 5   Student Response Rate              994 non-null    Int64
 6   Total Safety and Respect Score     1667 non-null   float64
 7   Total Communication Score          1667 non-null   float64
 8   Total Engagement Score             1667 non-null   float64
 9   Total Academic Expectations Score  1667 non-null   float64
dtypes: Int64(3), float64(4), object(3)
memory usage: 148.1+ KB

In [ ]:
# Calculate and display the percentage of missing (null) values for each column in the DataFrame
# This helps identify data quality issues and assess the need for cleaning or imputation
print(f"Counts of null values (as percentage of total rows): \n{df.isnull().sum() / len(df) * 100}")

In [ ]:
# Replace missing values in the 'Student Response Rate' column with 0
df['Student Response Rate'].fillna(0, inplace=True)

# Display a concise summary of the DataFrame, including column types and non-null counts
df.info()

#**2. Exploratory Data Analysis**

In [ ]:
# Iterate through all columns in the DataFrame
# For each column, print its name and display the frequency count of each unique value
# This is useful for understanding the distribution of categorical and discrete data
for col in df.columns:
    print(f'================= {col} =================')
    print(f'{df[col].value_counts()}')

In [ ]:
# Display the number of unique values in each column of the DataFrame
# Useful for understanding the variability and cardinality of features
print(f"{df.nunique()}")

In [ ]:
# Generate descriptive statistics for all numerical columns in the DataFrame
# Includes metrics such as count, mean, standard deviation, min, max, and quartiles
df.describe()

In [ ]:
# Initialize the LabelEncoder
label_encoder = preprocessing.LabelEncoder()

# Specify the categorical columns to encode
cols_to_encode = ['DBN', 'School Type']

# Apply LabelEncoder to each specified column to convert categorical values to numeric labels
for col in cols_to_encode:
    df[col] = label_encoder.fit_transform(df[col])

# Display the first few rows of the encoded DataFrame to verify the transformation
df.head()

In [ ]:
# Set the size of the figure for better readability
plt.figure(figsize=(10, 8))

# Generate a heatmap to visualize the correlation matrix between variables
# 'annot=True' displays the correlation coefficients on the heatmap
# 'cmap="coolwarm"' sets the color scheme
# 'fmt=".2f"' formats the correlation values to two decimal places
sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")

# Set the title of the heatmap
plt.title('Correlation Matrix Between Variables')

# Display the heatmap
plt.show()

#**3. Deep Dive**

In [ ]:
# Group the data by 'Parent Response Rate' and 'Total Communication Score' and count the number of occurrences
# This helps to analyze how frequently each combination appears
Parent = df.groupby(['School Type']).size()

# Sort the grouped data in descending order for better visualization
Parent_sorted = Parent.sort_values(ascending=False)

# Plotting the grouped and sorted data as a bar chart
plt.figure(figsize=(22, 9))
Parent_sorted.plot(kind='bar', linewidth=2)

# Set title and axis labels with proper formatting
plt.title('Distribution of School Type', fontsize=24)
plt.xlabel('School Type', fontsize=18)
plt.ylabel('Number of Occurrences', fontsize=18)

In [ ]:
# Group by 'School Type' and calculate the mean for the selected columns
school_scores = df.groupby('School Type')[[
    'Total Safety and Respect Score',
    'Total Communication Score',
    'Total Engagement Score',
    'Total Academic Expectations Score'
]].mean().reset_index()

# Display the final combined DataFrame
school_scores

In [ ]:
# List of score columns to analyze the impact of School Type
score_columns = [
    'Total Safety and Respect Score',
    'Total Communication Score',
    'Total Engagement Score',
    'Total Academic Expectations Score'
]

# Create a 2x2 grid of subplots to visualize all scores side-by-side
fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# Loop through each score column and corresponding subplot axis
for ax, col in zip(axes.flat, score_columns):
    # Draw a boxplot showing the distribution of scores by School Type
    sns.barplot(x='School Type', y=col, data=df, ax=ax)

    # Set title and axis labels for clarity
    ax.set_title(f'Impact of School Type on {col}', fontsize=14)
    ax.set_xlabel('School Type', fontsize=12)
    ax.set_ylabel(col, fontsize=12)

    # Rotate x-axis labels for better readability
    ax.tick_params(axis='x', rotation=45)

# Adjust layout to prevent overlap of plot elements
plt.tight_layout()

# Display all boxplots in a single figure window
plt.show()

In [ ]:
# Create a 2x2 grid of subplots for comparing multiple variables in one window
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Define the target metrics to compare with Parent Response Rate
metrics = [
    'Total Communication Score',
    'Total Engagement Score',
    'Total Academic Expectations Score',
    'Total Safety and Respect Score'
]

# Define corresponding titles for each subplot for clarity
titles = [
    'Parent Response vs Communication',
    'Parent Response vs Engagement',
    'Parent Response vs Academic Expectations',
    'Parent Response vs Safety and Respect'
]

# Loop over each axis, metric, and title to create individual scatter plots
for ax, metric, title in zip(axes.flat, metrics, titles):
    # Scatter plot showing the relationship between Parent Response Rate and the current metric
    ax.scatter(df['Parent Response Rate'], df[metric], alpha=0.6, edgecolors='k')

    # Set subplot title and axis labels for readability
    ax.set_title(title, fontsize=14)
    ax.set_xlabel('Parent Response Rate', fontsize=12)
    ax.set_ylabel(metric, fontsize=12)

# Adjust layout to prevent overlapping of elements
plt.tight_layout()

# Display all plots in a single window
plt.show()

In [ ]:
# Create a 2x2 grid of subplots for comparing multiple variables in one window
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Define the target metrics to compare with Parent Response Rate
metrics = [
    'Total Communication Score',
    'Total Engagement Score',
    'Total Academic Expectations Score',
    'Total Safety and Respect Score'
]

# Define corresponding titles for each subplot for clarity
titles = [
    'Teacher Response vs Communication',
    'Teacher Response vs Engagement',
    'Teacher Response vs Academic Expectations',
    'Teacher Response vs Safety and Respect'
]

# Loop over each axis, metric, and title to create individual scatter plots
for ax, metric, title in zip(axes.flat, metrics, titles):
    # Scatter plot showing the relationship between Parent Response Rate and the current metric
    ax.scatter(df['Teacher Response Rate'], df[metric], alpha=0.6, edgecolors='k')

    # Set subplot title and axis labels for readability
    ax.set_title(title, fontsize=14)
    ax.set_xlabel('Teacher Response Rate', fontsize=12)
    ax.set_ylabel(metric, fontsize=12)

# Adjust layout to prevent overlapping of elements
plt.tight_layout()

# Display all plots in a single window
plt.show()

In [ ]:
# Create a 2x2 grid of subplots for comparing multiple variables in one window
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Define the target metrics to compare with Parent Response Rate
metrics = [
    'Total Communication Score',
    'Total Engagement Score',
    'Total Academic Expectations Score',
    'Total Safety and Respect Score'
]

# Define corresponding titles for each subplot for clarity
titles = [
    'Student Response vs Communication',
    'Student Response vs Engagement',
    'Student Response vs Academic Expectations',
    'Student Response vs Safety and Respect'
]

# Loop over each axis, metric, and title to create individual scatter plots
for ax, metric, title in zip(axes.flat, metrics, titles):
    # Scatter plot showing the relationship between Parent Response Rate and the current metric
    ax.scatter(df['Student Response Rate'], df[metric], alpha=0.6, edgecolors='k')

    # Set subplot title and axis labels for readability
    ax.set_title(title, fontsize=14)
    ax.set_xlabel('Student Response Rate', fontsize=12)
    ax.set_ylabel(metric, fontsize=12)

# Adjust layout to prevent overlapping of elements
plt.tight_layout()

# Display all plots in a single window
plt.show()